spring:
  datasource:
    url: jdbc:postgresql://db.apqthfmjhnwxabmghaqk.supabase.co:5432/postgres
    username: postgres
    password: 1998+
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false