  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/MaFederation
      username: postgres
      password: az
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false